### ISSUE TITLE
有没有搭建成功的看看？

### ISSUE THREAD

**Issue by Maynor110** [jyx04/oaifree_helper#2]
到这一步卡住了
![image](https://github.com/jyx04/oaifree-helper/assets/171145485/c805484a-97ea-4714-b7cd-1bc251238fd7)

**Comment by jyx04** [comment]
你这已经搭建成功了呀，token management里加号，user management里加用户，就能用了

**Comment by shyboy** [comment]
> 你这已经搭建成功了呀，token management里加号，user management里加用户，就能用了

加号的时候显示Please complete the verification.大佬能不能在英文字段框里面加上填写说明啊

**Comment by jyx04** [comment]
account number是车号。填写说明在环境变量那一节里都有，不会在面板内再加

**Comment by Maynor110** [comment]
> 你这已经搭建成功了呀，token management里加号，user management里加用户，就能用了
这里是没有权限的意思吗
![image](https://github.com/jyx04/oaifree-helper/assets/171145485/8b35caff-da99-4d5e-ae29-f6836b6c1747)

**Comment by jyx04** [comment]
对，你的管理员密码
